// +build integration
// Code generated by "stringer -type ServerType"; DO NOT EDIT.

package sshserver

import "strconv"

const _ServerType_name = "OpenSSHGliderLabs"

var _ServerType_index = [...]uint8{0, 7, 17}

func (i ServerType) String() string {
	if i >= ServerType(len(_ServerType_index)-1) {
		return "ServerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerType_name[_ServerType_index[i]:_ServerType_index[i+1]]
}
