// Code generated by "stringer -type Signal"; DO NOT EDIT.

package signal

import "strconv"

const _Signal_name = "SIGABRTSIGALRMSIGFPESIGHUPSIGILLSIGINTSIGKILLSIGPIPESIGQUITSIGSEGVSIGTERMSIGUSR1SIGUSR2"

var _Signal_index = [...]uint8{0, 7, 14, 20, 26, 32, 38, 45, 52, 59, 66, 73, 80, 87}

func (i Signal) String() string {
	if i >= Signal(len(_Signal_index)-1) {
		return "Signal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Signal_name[_Signal_index[i]:_Signal_index[i+1]]
}
